# Generated by Django 5.0.4 on 2026-06-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_book_exercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
