# Generated by Django 5.0.4 on 2026-06-28 20:03

from django.db import migrations

def set_price(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")

    for s in smartphone_model.objects.all():
        new_price = len(s.brand) * 120
        s.price = new_price
        s.save()

def reverse_set_price(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")
    default_price = smartphone_model._meta.get_field("price").default

    for s in smartphone_model.objects.all():
        s.price = default_price
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=set_price,
            reverse_code=reverse_set_price
        )
    ]
