# Generated by Django 5.0.4 on 2026-08-04 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
