# Generated by Django 5.0.4 on 2026-06-27 07:57

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    shoe_model = apps.get_model("main_app", "Shoe")  # creates the model
    unique_brands_model = apps.get_model("main_app", "UniqueBrands")

    # gets the distinct brands as a list
    unique_brands_list: list[str] = shoe_model.objects.values_list('brand', flat=True).distinct()

    # adds the distinct brands into the unique brands model
    unique_brands_to_create = [unique_brands_model(brand_name=b) for b in unique_brands_list]
    # bulk adds them to the db
    unique_brands_model.objects.bulk_create(unique_brands_to_create)

def reverse_create_unique_brands(apps, schema_editor):
    unique_brands_model = apps.get_model("main_app", "UniqueBrands")
    unique_brands_model.objects.all().delete() # deletes all entries

class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(
            code=create_unique_brands,
            reverse_code=reverse_create_unique_brands,
        )
    ]
