# Generated by Django 5.0.4 on 2026-06-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release',
            new_name='release_year',
        ),
    ]
