# Generated by Django 5.0.4 on 2026-06-28 08:26

from django.db import migrations


def assign_age_group(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")
    for p in person_model.objects.all():
        if p.age <= 12:
            p.age_group = "Child"
        elif p.age <= 17:
            p.age_group = "Teen"
        elif p.age >= 18:
            p.age_group = "Adult"

        p.save()


def reverse_assign_age_group(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")
    default_age_group = person_model._meta.get_field("age_group").default

    for p in person_model.objects.all():
        p.age_group = default_age_group

        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [
        migrations.RunPython(
            code=assign_age_group,
            reverse_code=reverse_assign_age_group,
        )
    ]
