# Generated by Django 5.0.4 on 2026-06-28 19:06

from django.db import migrations

def set_item_rarity(apps, schema_editor):
    item_model = apps.get_model("main_app", "Item")

    for i in item_model.objects.all():
        if i.price < 11:
            i.rarity = "Rare"
        elif i.price < 21:
            i.rarity = "Very Rare"
        elif i.price < 31:
            i.rarity = "Extremely Rare"
        else:
            i.rarity = "Mega Rare"

        i.save()

def reverse_set_item_rarity(apps, schema_editor):
    item_model = apps.get_model("main_app", "Item")
    default_rarity = item_model._meta.get_field("rarity").default

    for i in item_model.objects.all():
        i.rarity = default_rarity
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_item'),
    ]

    operations = [
        migrations.RunPython(
            code=set_item_rarity,
            reverse_code=reverse_set_item_rarity,
        )
    ]
