# Generated by Django 5.0.4 on 2026-06-28 20:20

from django.db import migrations


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")

    for s in smartphone_model.objects.all():
        s.category = "Cheap" if s.price < 750 else "Expensive"
        s.save()


def reverse_set_category(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")
    default_category = smartphone_model._meta.get_field("category").default

    for s in smartphone_model.objects.all():
        s.category = default_category
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_migrate_smartphone_price'),
    ]

    operations = [
        migrations.RunPython(
            code=set_category,
            reverse_code=reverse_set_category
        )
    ]
