# Generated by Django 5.0.4 on 2026-06-28 20:56
from datetime import timedelta

from django.db import migrations

def execute_changes_by_status(apps, schema_editor):
    OrderModel = apps.get_model("main_app", "Order")

    for o in OrderModel.objects.filter(status="PE"):
        if o.order_date:
            o.delivery = o.order_date + timedelta(days=3)
            o.save()

    OrderModel.objects.filter(status="CO").update(warranty="24 months")
    OrderModel.objects.filter(status="CA").delete()

def reverse_execute_changes_by_status(apps, schema_editor):
    OrderModel = apps.get_model("main_app", "Order")

    OrderModel.objects.filter(status="PE").update(delivery=None)
    OrderModel.objects.filter(status="CO").update(warranty="No warranty")
    # For status CA the deleted entries cannot be restored.


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_order'),
    ]

    operations = [
        migrations.RunPython(
            code=execute_changes_by_status,
            reverse_code=reverse_execute_changes_by_status
        )
    ]
